services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=${VITE_SERVER_URL:-http://localhost:5027}
        - VITE_INDEXED_DB_VERSION=${VITE_INDEXED_DB_VERSION:-1}
        - VITE_API_KEY=${VITE_API_KEY}
        - VITE_INDEXED_DB_NAME=${VITE_INDEXED_DB_NAME:-expertbridge.duckdns.org}
        - VITE_AUTH_DOMAIN=${VITE_AUTH_DOMAIN}
        - VITE_PROJECT_ID=${VITE_PROJECT_ID}
        - VITE_STORAGE_BUCKET=${VITE_STORAGE_BUCKET}
        - VITE_MESSAGING_SENDER_ID=${VITE_MESSAGING_SENDER_ID}
        - VITE_APP_ID=${VITE_APP_ID}
        - VITE_MEAUSUREMENT_ID=${VITE_MEAUSUREMENT_ID}
        - VITE_ENABLE_DEBUG_LOGGING=${VITE_ENABLE_DEBUG_LOGGING:-true}
        - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-60000}
        - VITE_MAX_API_RETRIES=${VITE_MAX_API_RETRIES:-3}
        - VITE_ENABLE_TOKEN_MONITOR=${VITE_ENABLE_TOKEN_MONITOR:-true}
        - VITE_ENABLE_AUTH_MONITOR=${VITE_ENABLE_AUTH_MONITOR:-true}
        - VITE_ENABLE_PERFORMANCE_MONITORING=${VITE_ENABLE_PERFORMANCE_MONITORING:-true}
        - VITE_ENABLE_REACT_DEVTOOLS=${VITE_ENABLE_REACT_DEVTOOLS:-true}
        - VITE_ENABLE_REDUX_DEVTOOLS=${VITE_ENABLE_REDUX_DEVTOOLS:-true}
    container_name: expertbridge-client
    env_file:
      - .env
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - expertbridge-network

networks:
  expertbridge-network:
    driver: bridge
