services:
  Postgresql:
    image: "postgres:17-alpine"
    container_name: "Postgresql"
    volumes:
      - "expertbridge-postgresql-data:/var/lib/postgresql/data"
    ports:
        - target: 5432
          published: 5432
    env_file:
      - ".env.postgres"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
        - expert-bridge-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  Redis:
    container_name: "Redis"
    image: "docker.io/redis:alpine"
    volumes:
    - "expertbridge-redis-data:/data"
    ports:
    - target: 6379
      published: 4001
    command:
    - "--save"
    - "300"
    - "1"
    networks: 
      - expert-bridge-network
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  ExpertBridgeApi:
    container_name: "ExpertBridgeApi"
    image: "expertbridge-api:test"
    build:
      context: .
      dockerfile: "server/ExpertBridge.Api/Dockerfile"
    env_file:
      - ".env.api"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY}
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: ${ASPNETCORE_FORWARDEDHEADERS_ENABLED}
      HTTP_PORTS: ${HTTP_PORTS}
      ConnectionStrings__ExpertBridgeDb: ${ConnectionStrings__ExpertBridgeDb}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
    networks: 
      - expert-bridge-network
    ports:
    - target: 8080
      published: 10000
    depends_on:
      - Postgresql
      - Redis
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://ExpertBridgeApi:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ExpertBridgeClient:
    container_name: "ExpertBridgeClient"
    image: "expertbridge-client:test"
    build:
      context: .
      dockerfile: "client/Dockerfile"
    env_file:
      - ".env.client"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    networks: 
      - expert-bridge-network
    volumes:
      - "expertbridge-client-static-files:/client/dist"
    depends_on:
      - ExpertBridgeApi
    restart: unless-stopped

  NginxReverseProxy:
    container_name: "NginxReverseProxy"
    image: "nginx:alpine"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "expertbridge-client-static-files:/usr/share/nginx/html"
    ports:
      - target: 80
        published: 80
      - target: 8070
        published: 8070
    networks:
      - expert-bridge-network
    depends_on:
      - ExpertBridgeApi
      - ExpertBridgeClient
    restart: unless-stopped

volumes:
  expertbridge-postgresql-data:
    name: "expertbridge-postgresql-data"
    driver: local
  expertbridge-redis-data:
    name: "expertbridge-redis-data"
    driver: local
  expertbridge-client-static-files:
    name: "expertbridge-client-static-files"
    driver: local

networks:
  expert-bridge-network:
    name: "expert-bridge-network"
    driver: bridge
