services:
  SqlServer:
    container_name: "SqlServer"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    env_file:
      - ".env.mssql"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
      TrustServerCertificate: ${TrustServerCertificate}
    volumes:
    - "expertbridge-sqlserver-data:/var/opt/mssql"
    - "expertbridge-sqlserver-error-logs:/var/opt/mssql/log/errorlog"
    networks: 
      - expert-bridge-network
    ports:
    - target: 1433
      published: 4000
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  Redis:
    container_name: "Redis"
    image: "docker.io/redis:alpine"
    volumes:
    - "expertbridge-redis-data:/data"
    ports:
    - target: 6379
      published: 4001
    command:
    - "--save"
    - "300"
    - "1"
    networks: 
      - expert-bridge-network
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  ExpertBridgeApi:
    container_name: "ExpertBridgeApi"
    image: "expertbridge-api:test"
    build:
      context: .
      dockerfile: "server/ExpertBridge.Api/Dockerfile"
    env_file:
      - ".env.api"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY}
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: ${ASPNETCORE_FORWARDEDHEADERS_ENABLED}
      HTTP_PORTS: ${HTTP_PORTS}
      ConnectionStrings__TodoDb: ${ConnectionStrings__TodoDb}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
    networks: 
      - expert-bridge-network
    ports:
    - target: 8080
      published: 10000
    depends_on:
      - SqlServer
      - Redis
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://ExpertBridgeApi:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ExpertBridgeClient:
    container_name: "ExpertBridgeClient"
    image: "expertbridge-client:test"
    build:
      context: .
      dockerfile: "client/Dockerfile"
    env_file:
      - ".env.client"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    networks: 
      - expert-bridge-network
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - target: 80
      published: 10001
    restart: unless-stopped

volumes:
  expertbridge-sqlserver-data: {}
  expertbridge-sqlserver-error-logs: {}
  expertbridge-redis-data: {}

networks:
  expert-bridge-network:
    driver: bridge
    name: "expert-bridge-network"