services:
  Redis:
    container_name: "RedisCache"
    image: "redis:alpine"
    volumes:
    - "expertbridge-redis-data:/data"
    ports:
    - target: 6379
      published: 4001
    command:
    - "--save"
    - "300"
    - "1"
    networks: 
      - expert-bridge-network
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  ExpertBridgeApi:
    container_name: "ExpertBridgeApi"
    image: "expertbridge-api:latest"
    env_file:
      - ".env.api"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: ${OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY}
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: ${ASPNETCORE_FORWARDEDHEADERS_ENABLED}
      HTTP_PORTS: ${HTTP_PORTS}
      ConnectionStrings__TodoDb: ${ConnectionStrings__TodoDb}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
    networks: 
      - expert-bridge-network
    ports:
    - target: 8080
      published: 10000
    depends_on:
      - SqlServer
      - Redis
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://ExpertBridgeApi:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ExpertBridgeClient:
    container_name: "ExpertBridgeClient"
    image: "expertbridge-client:latest"
    env_file:
      - ".env.client"
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    volumes:
      - "expertbridge-client-static-files:/client/dist"
    networks: 
      - expert-bridge-network
    restart: unless-stopped

  NginxReverseProxy:
    container_name: "NginxReverseProxy"
    image: "nginx:stable-alpine"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "expertbridge-client-static-files:/usr/share/nginx/html"
    ports:
      - target: 80
        published: 80
      - target: 8070
        published: 8070
    networks:
      - expert-bridge-network
  
volumes:
  expertbridge-redis-data: 
    name: "expertbridge-redis-data"
    driver: local
    
  expertbridge-client-static-files:
    name: "expertbridge-client-static-files"
    driver: local

networks:
  expert-bridge-network:
    driver: bridge
    name: "expert-bridge-network"