global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add more scrape configurations as needed
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
          # - alertmanager:9093

# Optional: Add rules for alerting
# rule_files:
  # - "alerts.yml"