services:
  expertbridge.api:
    image: expertbridge-api:dev
    container_name: expertbridge-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5027:8080"

  expertbridge.admin:
    image: expertbridge.admin
    build:
      context: .
      dockerfile: Admin/Dockerfile

  expertbridge.worker:
    image: expertbridge.worker
    build:
      context: .
      dockerfile: ExpertBridge.Worker/Dockerfile

